apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: github build actions
inputs:
  url:  # id of input
    description: 'github action url'
    required: false
    default: 'https://api.github.com'
  token:  # id of input
    description: 'token'
    required: true
  org-name:  # id of input
    description: 'organization name'
    required: true
  repo-name:  # id of input
    description: 'repo name'
    required: true
  branch-name:  # id of input
    description: 'branch name'
    required: true
  workflow-name:  # id of input
    description: 'workflow name to run'
    required: true
  test-type:  # id of input
    description: 'test type'
    required: false
    default: ''
  test-result-location:  # id of input
    description: 'test result location'
    required: false
    default: ''
  parameters:  # id of input
    description: 'parameters as json'
    required: false
    default: '{}'
  
runs:
  using: composite
  steps:
    - id: invoke-github-job
      name: invoke-github-job
      uses: docker://public.ecr.aws/l7o7z1g8/actions/github-actions:main-960ba805ba016383185ecef9df6c2cb2a2345283
      shell: sh
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./github_actions_app invoke -b '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"GITHUBACTIONS","username":"","password":"${{ inputs.token }}","orgname":"${{ inputs.org-name }}","reponame":"${{ inputs.repo-name }}","branchname":"${{ inputs.branch-name }}","jobName":"${{ inputs.workflow-name }}","testType":"${{ inputs.test-type }}","fileName":"${{ inputs.test-result-location }}","parameters":${{ inputs.parameters }}}}'
        
        
